import type { OOHBootstrap, OOHSurveyQuestion } from './types';

export const oohSurveyQuestions: OOHSurveyQuestion[] = [
  { id: 'qr', label: 'Scan asset QR or NFC tag', type: 'text', required: true },
  { id: 'gps', label: 'Confirm GPS position within accepted tolerance', type: 'gps', required: true },
  { id: 'creative', label: 'Creative installed matches campaign booking', type: 'pass_fail', required: true, evidenceRequired: true },
  { id: 'condition', label: 'Structure, frame, vinyl or screen condition', type: 'pass_fail', required: true },
  { id: 'lighting', label: 'Illumination, power and player status', type: 'single_choice', required: true, options: ['Online', 'Needs attention', 'Not applicable'] },
  { id: 'photo', label: 'Capture wide, close-up and angle photos', type: 'photo', required: true, evidenceRequired: true },
  { id: 'signature', label: 'Field supervisor sign-off', type: 'signature', required: true },
];

const iso = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

export const fallbackOOHBootstrap: OOHBootstrap = {
  assets: [
    {
      id: 'OOH-DXB-SZR-001',
      name: 'Sheikh Zayed Road Mega Billboard',
      format: 'Unipole billboard',
      dimensions: '18m x 6m',
      market: 'Dubai',
      route: 'E11 Sheikh Zayed Road',
      address: 'Trade Centre corridor, Dubai',
      lat: 25.2186,
      lng: 55.2815,
      owner: 'OOH Assets',
      status: 'Live',
      permitStatus: 'Valid',
      permitExpiry: iso(118),
      illumination: 'Front-lit',
      powerStatus: 'Online',
      playerStatus: 'Not Installed',
      client: 'Emirates Retail Bank',
      campaign: 'Premium Miles Launch',
      buyerContact: 'Aisha Rahman, Brand Marketing',
      bookedFrom: iso(-14),
      bookedTo: iso(16),
      installSla: 'Installed 18h before go-live',
      proofSla: 'Proof approved within 4h',
      playerUptime: 100,
      audienceReference: 'Premium commuter corridor, audited GPS panel',
      lastClientView: iso(-1),
      installStatus: 'Installed',
      evidenceStatus: 'Ready',
      healthScore: 96,
      lastSurveyAt: iso(-2),
      nextSurveyDue: iso(12),
      attributes: ['High visibility', 'Northbound', 'Night illumination', 'Premium route'],
      evidence: [
        {
          id: 'EVD-SZR-001-A',
          type: 'photo',
          label: 'Wide angle installation proof',
          capturedAt: iso(-2),
          capturedBy: 'Falcon Field Team',
          gps: { lat: 25.2186, lng: 55.2815 },
          notes: 'Creative installed and illuminated.',
          photoCategory: 'Wide',
          qrVerified: true,
          gpsAccuracyMeters: 4,
          offlineCaptured: false,
          syncStatus: 'Synced',
          clientPublishStatus: 'Published',
          status: 'Approved',
        },
      ],
      surveyHistory: [{ id: 'SUB-SZR-001', date: iso(-2), score: 96, status: 'Approved', issues: [] }],
    },
    {
      id: 'OOH-DXB-MALL-014',
      name: 'Dubai Mall Arrival Digital Screen',
      format: 'Digital screen',
      dimensions: '6m x 3m LED',
      market: 'Dubai',
      route: 'Downtown visitor loop',
      address: 'Dubai Mall arrival zone',
      lat: 25.1972,
      lng: 55.2796,
      owner: 'OOH Assets',
      status: 'Booked',
      permitStatus: 'Valid',
      permitExpiry: iso(74),
      illumination: 'Digital',
      powerStatus: 'Online',
      playerStatus: 'Online',
      client: 'Nova Motors',
      campaign: 'EV Night Drive',
      buyerContact: 'Leila Mansour, Media Lead',
      bookedFrom: iso(-3),
      bookedTo: iso(27),
      installSla: 'Installed on time',
      proofSla: 'Close-up proof overdue',
      playerUptime: 98.7,
      audienceReference: 'Mall arrival loop, high dwell visitor traffic',
      lastClientView: iso(-2),
      installStatus: 'Installed',
      evidenceStatus: 'Pending',
      healthScore: 89,
      lastSurveyAt: iso(-7),
      nextSurveyDue: iso(3),
      attributes: ['Digital loop', 'Player ID LED-DM-014', '15-second slot', 'Mall traffic'],
      evidence: [],
      surveyHistory: [{ id: 'SUB-MALL-014', date: iso(-7), score: 89, status: 'Pending Review', issues: ['One proof angle pending'] }],
    },
    {
      id: 'OOH-AUH-COR-022',
      name: 'Corniche Bridge Banner',
      format: 'Bridge banner',
      dimensions: '24m x 2.8m',
      market: 'Abu Dhabi',
      route: 'Corniche Road',
      address: 'Corniche bridge approach',
      lat: 24.4748,
      lng: 54.3407,
      owner: 'Municipal concession',
      status: 'Install Due',
      permitStatus: 'Expiring',
      permitExpiry: iso(18),
      illumination: 'Non-illuminated',
      powerStatus: 'Not Required',
      playerStatus: 'Not Installed',
      client: 'Etihad Holidays',
      campaign: 'Summer Stopover',
      buyerContact: 'Omar Saeed, Tourism Partnerships',
      bookedFrom: iso(2),
      bookedTo: iso(32),
      installSla: 'Install due in 48h',
      proofSla: 'Proof required before go-live',
      playerUptime: 100,
      audienceReference: 'Corniche route visibility, bridge format',
      lastClientView: iso(-9),
      installStatus: 'Scheduled',
      evidenceStatus: 'Missing',
      healthScore: 82,
      lastSurveyAt: iso(-28),
      nextSurveyDue: iso(1),
      attributes: ['Permit renewal watch', 'Bridge crew required', 'Wind-load checklist'],
      evidence: [],
      surveyHistory: [{ id: 'SUB-COR-022', date: iso(-28), score: 82, status: 'Approved', issues: ['Permit expires within 30 days'] }],
    },
    {
      id: 'OOH-SHJ-BUS-033',
      name: 'Al Majaz Bus Shelter',
      format: 'Bus shelter',
      dimensions: '4-sheet backlit',
      market: 'Sharjah',
      route: 'Al Majaz Waterfront',
      address: 'Al Majaz stop 12',
      lat: 25.3272,
      lng: 55.3898,
      owner: 'OOH Assets',
      status: 'Survey Due',
      permitStatus: 'Valid',
      permitExpiry: iso(204),
      illumination: 'Back-lit',
      powerStatus: 'Online',
      playerStatus: 'Not Installed',
      client: 'CityPay',
      campaign: 'Tap and Go',
      buyerContact: 'Mina Kapoor, Growth',
      bookedFrom: iso(-20),
      bookedTo: iso(10),
      installSla: 'Installed on time',
      proofSla: 'Proof approved within 6h',
      playerUptime: 100,
      audienceReference: 'Pedestrian shelter panel with QR engagement',
      lastClientView: iso(-3),
      installStatus: 'Installed',
      evidenceStatus: 'Ready',
      healthScore: 91,
      lastSurveyAt: iso(-21),
      nextSurveyDue: iso(0),
      attributes: ['Pedestrian reach', 'Shelter glass', 'QR coupon panel'],
      evidence: [],
      surveyHistory: [{ id: 'SUB-BUS-033', date: iso(-21), score: 91, status: 'Approved', issues: [] }],
    },
    {
      id: 'OOH-DXB-JBR-047',
      name: 'JBR Promenade Wall Wrap',
      format: 'Wall wrap',
      dimensions: '32m x 9m',
      market: 'Dubai',
      route: 'JBR Walk',
      address: 'Beachfront promenade facade',
      lat: 25.0784,
      lng: 55.1352,
      owner: 'Private site owner',
      status: 'Issue',
      permitStatus: 'Pending',
      permitExpiry: iso(45),
      illumination: 'Static',
      powerStatus: 'Not Required',
      playerStatus: 'Not Installed',
      client: 'Luna Fashion',
      campaign: 'Resort Collection',
      buyerContact: 'Sofia Bell, Regional Marketing',
      bookedFrom: iso(-5),
      bookedTo: iso(25),
      installSla: 'Rework crew required',
      proofSla: 'Rejected proof blocks client sign-off',
      playerUptime: 100,
      audienceReference: 'JBR promenade footfall, premium wall wrap',
      lastClientView: iso(-1),
      installStatus: 'Needs Visit',
      evidenceStatus: 'Rejected',
      healthScore: 63,
      lastSurveyAt: iso(-1),
      nextSurveyDue: iso(2),
      attributes: ['High footfall', 'Facade access', 'Reprint likely'],
      evidence: [],
      surveyHistory: [{ id: 'SUB-JBR-047', date: iso(-1), score: 63, status: 'Rejected', issues: ['Corner lifting', 'Photo evidence blurred'] }],
    },
    {
      id: 'OOH-DXB-MET-061',
      name: 'Metro Station Totem',
      format: 'Street furniture',
      dimensions: '2m x 1.2m digital totem',
      market: 'Dubai',
      route: 'Metro Red Line',
      address: 'Business Bay station exit',
      lat: 25.1911,
      lng: 55.2606,
      owner: 'Transit media concession',
      status: 'Live',
      permitStatus: 'Valid',
      permitExpiry: iso(310),
      illumination: 'Digital',
      powerStatus: 'Online',
      playerStatus: 'Online',
      client: 'HealthPlus',
      campaign: 'Clinic Near You',
      buyerContact: 'Dr. Kareem Haddad, Marketing',
      bookedFrom: iso(-10),
      bookedTo: iso(20),
      installSla: 'Installed on time',
      proofSla: 'Proof approved within 3h',
      playerUptime: 99.4,
      audienceReference: 'Transit station totem with commuter dwell',
      lastClientView: iso(-2),
      installStatus: 'Installed',
      evidenceStatus: 'Ready',
      healthScore: 98,
      lastSurveyAt: iso(-3),
      nextSurveyDue: iso(11),
      attributes: ['Transit audience', 'Touch-safe glass', 'Player ID TOT-BB-061'],
      evidence: [],
      surveyHistory: [{ id: 'SUB-MET-061', date: iso(-3), score: 98, status: 'Approved', issues: [] }],
    },
  ],
  assignments: [
    {
      id: 'ASG-OOH-1001',
      name: 'Premium Miles proof-of-posting audit',
      assetIds: ['OOH-DXB-SZR-001', 'OOH-DXB-MALL-014'],
      team: 'Falcon Field Team',
      vendor: 'In-house',
      recurrence: 'Weekly',
      dueDate: iso(3),
      reviewer: 'Maya Haddad',
      status: 'Active',
      progress: 50,
      accessRules: { qrScan: true, gpsRequired: true, photoRequired: true, signatureRequired: true },
      questions: oohSurveyQuestions,
    },
    {
      id: 'ASG-OOH-1002',
      name: 'Corniche permit and install readiness check',
      assetIds: ['OOH-AUH-COR-022'],
      team: 'Capital Survey Crew',
      vendor: 'Abu Dhabi Partner',
      recurrence: 'One-time',
      dueDate: iso(1),
      reviewer: 'Omar Nasser',
      status: 'Active',
      progress: 0,
      accessRules: { qrScan: true, gpsRequired: true, photoRequired: true, signatureRequired: false },
      questions: oohSurveyQuestions,
    },
  ],
  submissions: [
    {
      id: 'SUB-OOH-9002',
      assignmentId: 'ASG-OOH-1001',
      assetId: 'OOH-DXB-MALL-014',
      submittedBy: 'Noura Saleh',
      submittedAt: iso(-1),
      gps: { lat: 25.1972, lng: 55.2796, label: 'Dubai Mall arrival zone' },
      score: 89,
      status: 'Pending Review',
      issues: ['One missing close-up proof angle'],
      answers: [
        { questionId: 'creative', question: 'Creative installed matches campaign booking', answer: 'Pass' },
        { questionId: 'lighting', question: 'Illumination, power and player status', answer: 'Online' },
        { questionId: 'photo', question: 'Capture wide, close-up and angle photos', answer: 'Two photos uploaded' },
      ],
      evidence: [
        {
          id: 'EVD-SUB-9002',
          type: 'photo',
          label: 'Digital screen proof pending review',
          capturedAt: iso(-1),
          capturedBy: 'Noura Saleh',
          gps: { lat: 25.1972, lng: 55.2796 },
          photoCategory: 'Angle',
          qrVerified: true,
          gpsAccuracyMeters: 6,
          offlineCaptured: false,
          syncStatus: 'Synced',
          clientPublishStatus: 'Internal Only',
          status: 'Pending Review',
        },
      ],
      reviewer: 'Maya Haddad',
      qrVerified: true,
      gpsAccuracyMeters: 6,
      photoCategories: ['Wide', 'Angle'],
      offlineCaptured: false,
      syncStatus: 'Synced',
      reviewerNotes: 'Request one close-up of LED playback frame before publishing.',
      clientPublishStatus: 'Internal Only',
    },
  ],
  clientPages: [
    {
      token: 'share-premium-miles',
      client: 'Emirates Retail Bank',
      campaign: 'Premium Miles Launch',
      title: 'Premium Miles Launch installation evidence',
      createdAt: iso(-1),
      expiresAt: iso(29),
      assetIds: ['OOH-DXB-SZR-001', 'OOH-DXB-MALL-014'],
      status: 'Live',
      proofReady: 1,
      surveyScore: 93,
      openItems: 1,
      watermarkLabel: '4C360 verified evidence',
      viewerCount: 7,
      lastViewedAt: iso(-1),
      accessState: 'Active',
      exportHistory: [
        { label: 'Campaign proof pack', at: iso(-1), by: 'Maya Haddad' },
      ],
      timeline: [
        { label: 'Assets booked', at: iso(-12), status: 'complete' },
        { label: 'Installation evidence submitted', at: iso(-2), status: 'complete' },
        { label: 'Client proof page published', at: iso(-1), status: 'complete' },
        { label: 'Close-up proof angle requested', at: iso(1), status: 'attention' },
      ],
    },
  ],
};
